### ISSUE TITLE
URL modificati

### ISSUE THREAD

**Issue by pippob02** [franthemanIT/parlaConINAD2#1]
riga 32: BASE_URL_AUTH = "[https://auth.uat.interop.pagopa.it/token.oauth2"](https://auth.uat.interop.pagopa.it/token.oauth2%22) #Ambiente PDND di produzione

riga 34: AUD_INTEROP = "auth.uat.interop.pagopa.it/client-assertion"

Gli url modificati e funzionanti sono questi ma continuiamo ad avere errore 401

**Comment by franthemanIT** [comment]
Ho provato adesso e in ambiente di produzione mi funziona.

401 e' lo status code per l'accesso non autorizzato. Hai provato a verificare la correttezza del voucher/token nel verificatore presente sul back office di Interoperabilità (PDND)?

**Comment by pippob02** [comment]
abbiamo risolto
grazie mille, è stato gentilissimo
